version: "3.8"

services:
  opensearch:
    image: opensearchproject/opensearch:2.12.0
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
    volumes:
      - ./data/opensearch:/usr/share/opensearch/data

  api:
    build: ./services/api
    environment:
      - DATA_ROOT=/data/parquet
      - OPENSEARCH_URL=http://opensearch:9200
      - REPORTING_URL=
      - OTEL_SERVICE_NAME=genomics-api
    depends_on:
      - opensearch
    ports:
      - "8000:8000"
    volumes:
      - ./data/parquet:/data/parquet:rw

  ui:
    build: ./ui
    environment:
      - NEXT_PUBLIC_API_BASE=http://localhost:8000
    depends_on:
      - api
    ports:
      - "3000:3000"

volumes:
  opensearch_data:
    driver: local